### ISSUE TITLE
No error/warning is displayed when files in `source` are not present

### ISSUE THREAD

**Issue by abelsromero** [chiquitinxx/grooscript-gradle-plugin#2]
When files in `source` param are not found the build completes with no warning or message at all.
In fact, gradle shows a BUILD SUCCESSFUL message but nothing happends.

I found this messing with the grooscript-gradle-plugin but imho this should be checked in the grooscript 'core' project. How about `addFileIfValid` method in GrooScript class validate if file exists?
Also, a 'strict' option could be added, when set to true, the process should abort with an exception, when set to false, it prints a warning. What do you think?

**Comment by chiquitinxx** [comment]
Agree any kind of warning has to be shown. In the grooscript core aye, when you call a 'conversion' and nothing is converted at least. I think about an exception if nothing is converted.

Dunno about if a list of files to be converted, and someone is not found, hard to say, you can convert folders, and even recursive. I prefer no exception, maybe some messages in console, but I don't like it too much. What do you prefer?

**Comment by abelsromero** [comment]
I'm not really a fan of using exceptions for everything. That's why I think, for now, a 'strict' option can be enough. More complex system can be done in the future, e.g. returning a result object with warnings and errors so that the invoking tool can take a desition.

When I think abot the strict solution its cause i'm thinking in 2 use case:
. development: in that case you don' want constant exceptions but you need to know what's going on. The problem is how to ensure the logging system works from gradle or any external tools invoking.
. CI builds: in that case you need to ensure that the package is correct, specially if testing is hard or not possible.

Using the current options map you can pass this option and later on, just log or throw an exception. This shouldn't be hard and you can still offer all possibilities

**Comment by abelsromero** [comment]
BTW, I can work some propotype If you want.

**Comment by chiquitinxx** [comment]
Sure, go for it :)
