### ISSUE TITLE
Demos fail when executed within eclipse IDE

### ISSUE THREAD

**Issue by abelsromero** [chiquitinxx/grooscript-gradle-plugin#3]
When executing a build with the eclipse's 'Gradle IDE ' plugin (from SpringSource) they complete successfully, but they don't execute the conversion of source files, see #2 for details.

This is caused because eclipse's plugin starts a gradle daemon setting as root folder eclipse's installation folder. Since GrooScript instantiates sources in the follwing way:
```
new File(source)
```
sources are searched inside eclipse's installation folder instead of the project's root, and this causes the problems described in #2.

I found this issue testing the demos project, as a workarroud I just prefixed sources and destination (I forgot, this issue affects destination too) with the project's path (project.projectDir):
```
task convertAsciidoctor(type: org.grooscript.gradle.ConvertTask) {
    source = ["${project.projectDir}/src/main/groovy/asciidoctor/AdocLive.groovy", "${project.projectDir}/src/main/groovy/startLiveAdoc.groovy"]
    destination = "${project.projectDir}/src/main/webapp/js2"
    classPath = ["${project.projectDir}/src/main/groovy"]
}
```

I see two possible solutions:
* Add overloaded `convert` methods that accept File as source/destination and use them in the plugin. Another option could be to accept File as `source` value since `source` has no type. However, even when using Groovy, I prefer to offer Java friendly interfaces to ease integration from Java. But this is just my opinion :P
* Deal with paths in the plugin ensuring that project.projectDir is appended to all parameters.

What do you think?

**Comment by chiquitinxx** [comment]
I have been working on this issue today. Yesterday, detected similar stuff working with multi project build. I have seen in the gradle doc, that they recommend use "Project.file(pathToFile)", I'm trying it. Is better I pre-proccess in the plugin and then you don't have to worry about that paths, just put relative paths.

**Comment by abelsromero** [comment]
I guess you mean passing the inputs through http://www.gradle.org/docs/current/javadoc/org/gradle/api/Project.html#file(java.lang.Object).
In that case, I'm wondering if it would make sense to work on more sophisticated ideas.

The same issue we raised some time ago in https://github.com/asciidoctor/asciidoctor-gradle-plugin/, in fact the problem is more or less the same. I don't know all details but maybe it would be worth checking it out.

**Comment by chiquitinxx** [comment]
In the grooscript-core, I have added a new convert method

```groovy
static void convert(List<File> sources, File destination)
```
That Project.file() seem works pretty well, and you don't have to worry about paths. I think is better set files and folders with strings that use new File() for each entry. I'll check asciidoctor plugin.

Thank you very much for your feedback :)

**Comment by abelsromero** [comment]
This is just to make sure I undestand. Unless I'm missing something, the paths should be previously parsed in the plugin. So, in https://github.com/chiquitinxx/grooscript-gradle-plugin/blob/master/src/main/groovy/org/grooscript/gradle/ConvertTask.groovy#L29
now will be:
```
GrooScript.convert(project.file(source), project.file(destination))
```

Right? Same for other taks like Templates.

Don't thank me, it is a must to report any bug or improvement to help.

**Comment by chiquitinxx** [comment]
Aye, all this work is in 1.0 branch, that uses grooscript next release rc-2(master branch)

https://github.com/chiquitinxx/grooscript-gradle-plugin/blob/1.0/src/main/groovy/org/grooscript/gradle/ConvertTask.groovy

**Comment by chiquitinxx** [comment]
Can you try with plugin version 0.10 or 0.11?

**Comment by chiquitinxx** [comment]
I suppose is working, so I close this issue.
